#!/bin/bash
# ==========================================================================
# generate_scaling_jobs.sh — Generate and optionally submit SLURM scripts
#                            for weak/strong GPU-scaling tests.
# ==========================================================================
#
# Usage:
#   ./generate_scaling_jobs.sh              # generate scripts only
#   ./generate_scaling_jobs.sh --submit     # generate AND sbatch each one
#
# What it does:
#   For each (nodes, gpus_per_node) combination, emit a self-contained
#   SLURM batch script under scaling_jobs/ and optionally submit it.
#
#   subsample_rate controls the number of patches per image per epoch.
#   With 16 training images, subsample_rate=S → 16*S samples/epoch.
#   DDP splits those across total_gpus, so batches/gpu = 16*S / (G * B).
#   Increase S so every GPU sees enough work to amortise sync overhead.
#
# Dodrio-specific:
#   - ntasks-per-node=1 so each task sees ALL its GPUs (cgroup trick)
#   - torchrun manages local DDP workers; c10d TCP rendezvous across nodes
#   - OMPI_MCA env vars prevent OpenMPI PMI crash (no SLURM PMI on Dodrio)
#   - CUDA_VISIBLE_DEVICES forced inside srun steps (multi-node only)
# ==========================================================================

set -euo pipefail

# ---- Tunable parameters --------------------------------------------------
LOGGER_NAME="CNN"  # trainer.logger.init_args.name
REPO_DIR="/dodrio/scratch/projects/2026_018/george/closure"
ACCOUNT="2026_018"
PARTITION="gpu_rome_a100"
CONFIG="configs/legacy_harris_4lrs_es500.yaml"
MAX_EPOCHS=50               # short runs for scaling benchmarks
BATCH_SIZE=32               # per-GPU batch size
BASE_SUBSAMPLE=160          # subsample_rate in the config (samples per image)
NUM_WORKERS=4               # DataLoader workers per rank
WALL_TIME="01:00:00"
CPUS_PER_TASK=8
MEM="64G"

# Network architecture (same for all runs, so results are comparable).
CHANNELS='[10,256,128,64,6]'
KERNELS='[5,5,3,3]'
ACTIVATIONS='[ReLU,ReLU,SiLU,null]'
BATCH_NORMS='[true,true,true,false]'

# Scaling configurations: "nodes gpus_per_node subsample_rate"
# subsample_rate is scaled up proportionally to total GPUs so each GPU
# sees roughly the same number of batches (weak scaling).
# For strong scaling, use the same subsample_rate everywhere.
SCALING_MODE="${SCALING_MODE:-strong}"   # "strong" or "weak"

CONFIGS=(
  "1 1"
  "1 2"
  "1 4"
  "2 2"
  "2 4"
  "4 4"
)
# --------------------------------------------------------------------------

SUBMIT=false
[[ "${1:-}" == "--submit" ]] && SUBMIT=true

OUT_DIR="$(cd "$(dirname "$0")" && pwd)/scaling_jobs"
mkdir -p "$OUT_DIR"

for cfg in "${CONFIGS[@]}"; do
  read -r NODES GPUS_PER_NODE <<< "$cfg"
  TOTAL_GPUS=$(( NODES * GPUS_PER_NODE ))

  if [[ "$SCALING_MODE" == "weak" ]]; then
    # Weak scaling: multiply subsample_rate by total GPUs so per-GPU
    # work stays constant as we add GPUs.
    SUBSAMPLE=$(( BASE_SUBSAMPLE * TOTAL_GPUS ))
  else
    # Strong scaling: fixed dataset, split across GPUs.
    SUBSAMPLE=$BASE_SUBSAMPLE
  fi

  TAG="${SCALING_MODE}_${NODES}n_${GPUS_PER_NODE}g"
  SCRIPT="${OUT_DIR}/scale_${TAG}.sh"

  # Decide launch strategy.
  if (( TOTAL_GPUS == 1 )); then
    LAUNCH_MODE="single"
  elif (( NODES == 1 )); then
    LAUNCH_MODE="torchrun_standalone"
  else
    LAUNCH_MODE="torchrun_multinode"
  fi

  cat > "$SCRIPT" <<SLURM_HEADER
#!/bin/bash
# Auto-generated by generate_scaling_jobs.sh — ${SCALING_MODE} scaling
# Config: ${NODES} node(s), ${GPUS_PER_NODE} GPU(s)/node = ${TOTAL_GPUS} GPUs total
# subsample_rate=${SUBSAMPLE}  (batches/gpu ≈ 16*${SUBSAMPLE}/${TOTAL_GPUS}/${BATCH_SIZE})
#SBATCH --job-name=scale_${TAG}
#SBATCH --account=${ACCOUNT}
#SBATCH --nodes=${NODES}
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:${GPUS_PER_NODE}
#SBATCH --cpus-per-task=${CPUS_PER_TASK}
#SBATCH --mem=${MEM}
#SBATCH --time=${WALL_TIME}
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err
#SBATCH --partition=${PARTITION}

set -euo pipefail

REPO_DIR="${REPO_DIR}"
cd "\$REPO_DIR"
mkdir -p logs

module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1
module load h5py/3.9.0-foss-2023a
module load torchvision/0.16.0-foss-2023a-CUDA-12.1.1
module load matplotlib/3.7.2-gfbf-2023a
module load PyTorch-Lightning/2.2.1-foss-2023a-CUDA-12.1.1

export PATH="\${REPO_DIR}/_shims:\${PATH}"
export PYTHONPATH="\${REPO_DIR}/_shims:\${REPO_DIR}:\${PYTHONPATH:-}"
export OMP_NUM_THREADS="\${SLURM_CPUS_PER_TASK:-1}"

export MPI4PY_RC_INITIALIZE=0
export OMPI_MCA_ess=singleton
export OMPI_MCA_plm=isolated

echo "=== Scaling test: ${TAG} ==="
echo "CUDA_VISIBLE_DEVICES=\${CUDA_VISIBLE_DEVICES:-<unset>}"
nvidia-smi -L || true
SLURM_HEADER

  # Shared sed replacements for all modes (applied at the end).
  do_sed() {
    local strategy="auto"
    (( TOTAL_GPUS > 1 )) && strategy="ddp"
    sed -i \
      -e "s|PLACEHOLDER_MAX_DEV|$(( GPUS_PER_NODE - 1 ))|g" \
      -e "s|PLACEHOLDER_GPUS|${GPUS_PER_NODE}|g" \
      -e "s|PLACEHOLDER_CONFIG|${CONFIG}|g" \
      -e "s|PLACEHOLDER_EPOCHS|${MAX_EPOCHS}|g" \
      -e "s|PLACEHOLDER_NODES|${NODES}|g" \
      -e "s|PLACEHOLDER_STRATEGY|${strategy}|g" \
      -e "s|PLACEHOLDER_BS|${BATCH_SIZE}|g" \
      -e "s|PLACEHOLDER_SS|${SUBSAMPLE}|g" \
      -e "s|PLACEHOLDER_NW|${NUM_WORKERS}|g" \
      -e "s|PLACEHOLDER_LN|${LOGGER_NAME}|g" \
      -e "s|PLACEHOLDER_TAG|${TAG}|g" \
      -e "s|PLACEHOLDER_CH|${CHANNELS}|g" \
      -e "s|PLACEHOLDER_KE|${KERNELS}|g" \
      -e "s|PLACEHOLDER_AC|${ACTIVATIONS}|g" \
      -e "s|PLACEHOLDER_BN|${BATCH_NORMS}|g" \
      "$SCRIPT"
  }

  case "$LAUNCH_MODE" in
    single)
      cat >> "$SCRIPT" <<'EOF'

# Single-GPU: srun enters the cgroup step; --cpu-bind=none avoids conflicts.
srun --cpu-bind=none closure-train fit \
  --config PLACEHOLDER_CONFIG \
  --trainer.max_epochs=PLACEHOLDER_EPOCHS \
  --trainer.devices=PLACEHOLDER_GPUS \
  --trainer.num_nodes=PLACEHOLDER_NODES \
  --trainer.strategy=PLACEHOLDER_STRATEGY \
  --trainer.enable_progress_bar=false \
  --data.batch_size=PLACEHOLDER_BS \
  --data.subsample_rate=PLACEHOLDER_SS \
  --data.num_workers=PLACEHOLDER_NW \
  --trainer.logger.init_args.name=PLACEHOLDER_LN \
  --trainer.logger.init_args.version=PLACEHOLDER_TAG \
  --model.network.init_args.channels='PLACEHOLDER_CH' \
  --model.network.init_args.kernels='PLACEHOLDER_KE' \
  --model.network.init_args.activations='PLACEHOLDER_AC' \
  --model.network.init_args.batch_norms='PLACEHOLDER_BN'
EOF
      do_sed
      ;;

    torchrun_standalone)
      cat >> "$SCRIPT" <<'EOF'

# Single-node multi-GPU: torchrun --standalone (TCP rendezvous, no MPI).
python -m torch.distributed.run \
  --standalone \
  --nproc_per_node=PLACEHOLDER_GPUS \
  --module closure.cli fit \
  --config PLACEHOLDER_CONFIG \
  --trainer.max_epochs=PLACEHOLDER_EPOCHS \
  --trainer.devices=PLACEHOLDER_GPUS \
  --trainer.num_nodes=PLACEHOLDER_NODES \
  --trainer.strategy=PLACEHOLDER_STRATEGY \
  --trainer.enable_progress_bar=false \
  --data.batch_size=PLACEHOLDER_BS \
  --data.subsample_rate=PLACEHOLDER_SS \
  --data.num_workers=PLACEHOLDER_NW \
  --trainer.logger.init_args.name=PLACEHOLDER_LN \
  --trainer.logger.init_args.version=PLACEHOLDER_TAG \
  --model.network.init_args.channels='PLACEHOLDER_CH' \
  --model.network.init_args.kernels='PLACEHOLDER_KE' \
  --model.network.init_args.activations='PLACEHOLDER_AC' \
  --model.network.init_args.batch_norms='PLACEHOLDER_BN'
EOF
      do_sed
      ;;

    torchrun_multinode)
      cat >> "$SCRIPT" <<'MNODE_SETUP'

# Multi-node: resolve master address, derive port from job ID.
MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
MASTER_PORT=$(( 20000 + SLURM_JOB_ID % 10000 ))
export MASTER_ADDR MASTER_PORT
echo "MASTER_ADDR=${MASTER_ADDR}  MASTER_PORT=${MASTER_PORT}"

MNODE_SETUP

      cat >> "$SCRIPT" <<'EOF'
# srun launches one torchrun per node. CUDA_VISIBLE_DEVICES forced
# inside the step to bypass Dodrio's cgroup GPU restriction.
srun --cpu-bind=none bash -c '
export CUDA_VISIBLE_DEVICES=$(seq -s, 0 PLACEHOLDER_MAX_DEV)
python -m torch.distributed.run \
  --nproc_per_node=PLACEHOLDER_GPUS \
  --nnodes='"$SLURM_NNODES"' \
  --node_rank="${SLURM_NODEID}" \
  --rdzv_id='"$SLURM_JOB_ID"' \
  --rdzv_backend=c10d \
  --rdzv_endpoint='"${MASTER_ADDR}:${MASTER_PORT}"' \
  --module closure.cli fit \
  --config PLACEHOLDER_CONFIG \
  --trainer.max_epochs=PLACEHOLDER_EPOCHS \
  --trainer.devices=PLACEHOLDER_GPUS \
  --trainer.num_nodes=PLACEHOLDER_NODES \
  --trainer.strategy=ddp \
  --trainer.enable_progress_bar=false \
  --data.batch_size=PLACEHOLDER_BS \
  --data.subsample_rate=PLACEHOLDER_SS \
  --data.num_workers=PLACEHOLDER_NW \
  --trainer.logger.init_args.name=PLACEHOLDER_LN \
  --trainer.logger.init_args.version=PLACEHOLDER_TAG \
  --model.network.init_args.channels='"'"'PLACEHOLDER_CH'"'"' \
  --model.network.init_args.kernels='"'"'PLACEHOLDER_KE'"'"' \
  --model.network.init_args.activations='"'"'PLACEHOLDER_AC'"'"' \
  --model.network.init_args.batch_norms='"'"'PLACEHOLDER_BN'"'"'
'
EOF
      do_sed
      ;;
  esac

  chmod +x "$SCRIPT"
  echo "Generated: $SCRIPT  [${LAUNCH_MODE}, ${TOTAL_GPUS} GPU(s), subsample=${SUBSAMPLE}]"

  if $SUBMIT; then
    sbatch "$SCRIPT"
  fi
done

echo ""
echo "=== Summary ==="
echo "Mode:   ${SCALING_MODE} scaling"
echo "Epochs: ${MAX_EPOCHS}"
echo "Batch:  ${BATCH_SIZE}"
if [[ "$SCALING_MODE" == "strong" ]]; then
  echo "Subsample rate: ${BASE_SUBSAMPLE} (fixed)"
  echo "Total samples/epoch: $((16 * BASE_SUBSAMPLE)) = 16 images × ${BASE_SUBSAMPLE}"
else
  echo "Base subsample: ${BASE_SUBSAMPLE} (scaled per total GPUs)"
fi
echo "Scripts in: ${OUT_DIR}/"
if ! $SUBMIT; then
  echo ""
  echo "To submit all:  $0 --submit"
  echo "To submit one:  sbatch ${OUT_DIR}/scale_<tag>.sh"
fi
